// Generated by the legend_of_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its character-art source are not versioned; see this
// example's README for what they are and where they live. Edit the art there
// and re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef CLONE_TILEMAP_PALETTE_H
#define CLONE_TILEMAP_PALETTE_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * @file TilemapPalette.h
 * @brief The 16 RGB565 colors both tilemaps render with.
 *
 * Installed with setBackgroundCustomPalette(). The engine stores the pointer
 * without copying, which is why this lives at namespace scope.
 *
 * Sampled to match the NES first-quest overworld: tan ground, the two greens
 * of the bushes and forest, the navy drop shadow under every bush, and the two
 * browns of the mountains.
 */

namespace legend_of_clone {

    // --- RGB565 by engine Color slot ---
    // Indexed by Color, NOT by 4bpp pixel value. Every color sits in its
    // conventional slot so Color::White is still white and Color::Red is still
    // red for anything that names a color instead of indexing art.
    static const uint16_t TILEMAP_PALETTE_DATA[16] = {
        0x0000, //  0 Black  'k'  #000000  outlines, cave mouth, dungeon floor
        0xFFFF, //  1 White  'w'  #FCFCFC  text, old man hair and beard, shopkeeper apron
        0x0015, //  2 Navy  'n'  #0000A8  drop shadow, dungeon wall mortar
        0x3DFF, //  3 Blue  'b'  #3CBCFC  dungeon wall block
        0xFCC7, //  4 Cyan  's'  #FC9838  skin - Link and the dungeon NPCs
        0x03C0, //  5 DarkGreen  'd'  #007800  foliage shading
        0x0540, //  6 Green  'g'  #00A800  foliage body
        0x8682, //  7 LightGreen  'l'  #80D010  Link's tunic, shopkeeper tunic
        0xEE94, //  8 Yellow  '.'  #E8D0A0  sand - the ground everything sits on
        0xAAA0, //  9 Orange  'o'  #A85400  mountain rock, lit face
        0xCA61, // 10 LightRed  'h'  #C84C0C  Link's brown - outline, hair, boots, belt; old man robe
        0xF9C0, // 11 Red - error text - must never resolve to black
        0x71C0, // 12 DarkRed  'r'  #703800  mountain rock, shaded face
        0x6A3F, // 13 Purple - unused
        0xBDDF, // 14 Magenta - unused
        0xBDF7, // 15 Gray  'y'  #BCBCBC  dungeon stairs, dimmed text
    };

    // --- 4bpp pixel value to engine Color slot ---
    // The blitter reads sprite.palette[pixelValue] as a Color and resolves that
    // slot against the table above. Entry 0 is never read: pixel value 0 is a
    // hole, which is why black has to live at pixel value 1 and not at 0.
    static const pixelroot32::graphics::Color TILEMAP_PALETTE_MAPPING[16] = {
        pixelroot32::graphics::Color::Black, //  0 transparent - never read
        pixelroot32::graphics::Color::Black, //  1 'k' -> Black
        pixelroot32::graphics::Color::White, //  2 'w' -> White
        pixelroot32::graphics::Color::Navy, //  3 'n' -> Navy
        pixelroot32::graphics::Color::Blue, //  4 'b' -> Blue
        pixelroot32::graphics::Color::Cyan, //  5 's' -> Cyan
        pixelroot32::graphics::Color::DarkGreen, //  6 'd' -> DarkGreen
        pixelroot32::graphics::Color::Green, //  7 'g' -> Green
        pixelroot32::graphics::Color::LightGreen, //  8 'l' -> LightGreen
        pixelroot32::graphics::Color::Yellow, //  9 '.' -> Yellow
        pixelroot32::graphics::Color::Orange, // 10 'o' -> Orange
        pixelroot32::graphics::Color::LightRed, // 11 'h' -> LightRed
        pixelroot32::graphics::Color::DarkRed, // 12 'r' -> DarkRed
        pixelroot32::graphics::Color::Gray, // 13 'y' -> Gray
        pixelroot32::graphics::Color::Black, // 14 unused
        pixelroot32::graphics::Color::Black, // 15 unused
    };

} // namespace legend_of_clone

#endif // CLONE_TILEMAP_PALETTE_H
