"""Exports the character art in art_source.py to the C++ under src/assets/.

This stands in for the PixelRoot32 Tilemap Editor and Sprite Compiler: it emits
the same shapes those tools emit, so the example's runtime code is the same code
you would write against real exported assets.

    python generate_assets.py [path/to/legend_of_clone]

Run it after editing art_source.py, then commit the result. The GENERATED files
are versioned; this exporter is not - it lives under docs/audits/, which is
gitignored, the same way the Tilemap Editor is not in the repository either.
An example has to build for someone who has never run a Python script.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import art_source as art  # noqa: E402
from locate import locate_example  # noqa: E402

OUT = locate_example() / "src" / "assets"

BANNER = """// Generated by the legend_of_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its character-art source are not versioned; see this
// example's README for what they are and where they live. Edit the art there
// and re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp
"""


# ---------------------------------------------------------------------------
# Packing
# ---------------------------------------------------------------------------

def build_palette(char_sets):
    """The characters one asset group uses, in art_source.COLORS order.

    Their position in this list is their 4bpp pixel value, offset by one: pixel
    value 0 is transparent, because the blitter treats it as a hole and never
    reads palette entry 0, so no character may land there.
    """
    used = set()
    for rows in char_sets:
        for line in rows:
            used.update(line)
    used.discard(art.TRANSPARENT)

    unknown = used - set(art.COLORS)
    if unknown:
        raise SystemExit(f"art uses characters with no color: {sorted(unknown)}")

    return [c for c in art.COLORS if c in used]


def palette_tables(chars):
    """Splits a character set into the exporter's two arrays.

    Returns (data, mapping):
      data[Color slot]   = RGB565
      mapping[pixel value] = Color slot

    Colors keep their conventional slots, so Color::White is still white for
    anything that names a color rather than indexing art.
    """
    data = [0x0000] * 16
    notes = [None] * 16

    for name, (rgb, why) in art.RESERVED_SLOTS.items():
        slot = art.SLOTS[name]
        data[slot] = rgb
        notes[slot] = f"{name} - {why}"

    for c in chars:
        rgb, name, comment = art.COLORS[c]
        slot = art.SLOTS[name]
        data[slot] = rgb
        notes[slot] = f"{name}  '{c}'  {comment}"

    mapping = [0] * 16
    for i, c in enumerate(chars):
        mapping[i + 1] = art.SLOTS[art.COLORS[c][1]]

    return data, notes, mapping


def pack(rows, palette):
    """Character art to packed 4bpp bytes.

    Nibble order follows the engine's blitter: within a byte the LOW nibble is
    the LEFT pixel of the pair and the high nibble is the right one. Getting
    this backwards mirrors every pair of pixels - art that looks almost right,
    which is harder to spot than art that looks broken.
    """
    index = {c: i + 1 for i, c in enumerate(palette)}
    out = bytearray()
    for row in rows:
        if len(row) != art.ART_SIZE:
            raise SystemExit(f"row is {len(row)} chars, expected {art.ART_SIZE}: {row!r}")
        for col in range(0, art.ART_SIZE, 2):
            left = index.get(row[col], 0)
            right = index.get(row[col + 1], 0)
            out.append((right << 4) | left)
    return bytes(out)


def to_words(data):
    """Packed bytes to the uint16_t array the Sprite Compiler emits.

    Little-endian: the first byte of a row is the low byte of the first word.
    Both supported targets (x86-64 and Xtensa) are little-endian, which is the
    assumption baked into the exporter's own output format.
    """
    if len(data) % 2:
        raise SystemExit("packed sprite data must be an even number of bytes")
    return [data[i] | (data[i + 1] << 8) for i in range(0, len(data), 2)]


# ---------------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------------

def doc_block(text, indent):
    """A multi-line doc comment, so long art notes survive the export intact."""
    lines = text.splitlines()
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    out = [f"{indent}/**"]
    out += [f"{indent} * {line}".rstrip() for line in lines]
    out.append(f"{indent} */")
    return out


def emit_palette_header(path, guard, doc, data_name, mapping_name, palette, note):
    lines = [
        BANNER,
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "graphics/Renderer.h"',
        "#include <stdint.h>",
        "",
        "/**",
        f" * @file {path.name}",
        f" * @brief {doc}",
        " *",
    ]
    lines += [f" * {line}".rstrip() for line in note.splitlines()]
    lines += [
        " */",
        "",
        "namespace legend_of_clone {",
        "",
        "    // --- RGB565 by engine Color slot ---",
        "    // Indexed by Color, NOT by 4bpp pixel value. Every color sits in its",
        "    // conventional slot so Color::White is still white and Color::Red is still",
        "    // red for anything that names a color instead of indexing art.",
        f"    static const uint16_t {data_name}[16] = {{",
    ]
    data, notes, mapping = palette_tables(palette)
    slot_names = {v: k for k, v in art.SLOTS.items()}
    for slot in range(16):
        note = notes[slot] or f"{slot_names[slot]} - unused"
        lines.append(f"        0x{data[slot]:04X}, // {slot:2d} {note}")
    lines += [
        "    };",
        "",
        "    // --- 4bpp pixel value to engine Color slot ---",
        "    // The blitter reads sprite.palette[pixelValue] as a Color and resolves that",
        "    // slot against the table above. Entry 0 is never read: pixel value 0 is a",
        "    // hole, which is why black has to live at pixel value 1 and not at 0.",
        f"    static const pixelroot32::graphics::Color {mapping_name}[16] = {{",
    ]
    for value in range(16):
        slot = mapping[value]
        if value == 0:
            why = "transparent - never read"
        elif value <= len(palette):
            why = f"'{palette[value - 1]}' -> {slot_names[slot]}"
        else:
            why = "unused"
        lines.append(f"        pixelroot32::graphics::Color::{slot_names[slot]}, "
                     f"// {value:2d} {why}")
    lines += [
        "    };",
        "",
        "} // namespace legend_of_clone",
        "",
        f"#endif // {guard}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_tilemap(name, ns, tiles, rows, legend, palette_header, mapping_name, doc):
    """Writes <name>TileMap.h / .cpp in the shape the Tilemap Editor exports."""
    guard_h = f"CLONE_{ns.upper()}_TILEMAP_H"

    tile_names = [t[0] for t in tiles]
    packed = [pack(t[3], palette) for t in tiles]
    tile_bytes = len(packed[0])

    # --- header ---
    h = [
        BANNER,
        f"#ifndef {guard_h}",
        f"#define {guard_h}",
        "",
        '#include "platforms/PlatformDefaults.h"',
        "",
        "#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES",
        "",
        '#include "graphics/Renderer.h"',
        "#include <stdint.h>",
        "",
        "/**",
        f" * @file {name}TileMap.h",
        f" * @brief {doc}",
        " */",
        "",
        "namespace legend_of_clone {",
        f"namespace {ns} {{",
        "",
        "    // --- Dimensions ---",
        f"    static const uint8_t  TILE_SIZE  = {art.ART_SIZE};",
        f"    static const uint8_t  MAP_WIDTH  = {art.MAP_COLS};",
        f"    static const uint8_t  MAP_HEIGHT = {art.MAP_ROWS};",
        f"    static const uint16_t TILE_COUNT = {len(tiles)};",
        "",
        "    // --- Tile ids ---",
        "    // 1-based: drawTileMap skips index 0, so slot 0 is reserved and never drawn.",
    ]
    for i, (tname, _solid, tdoc, _rows) in enumerate(tiles):
        h.append("")
        h += doc_block(tdoc, "    ")
        h.append(f"    static const uint8_t {tname} = {i};")
    h += [
        "",
        "    /**",
        "     * @brief Per-tile collision, indexed by tile id.",
        "     *",
        "     * Collision is a property of the tile here, not of a separate layer, so it",
        "     * is exported alongside the tileset and cannot drift away from the art.",
        "     */",
        "    extern const bool TILE_SOLID[TILE_COUNT];",
        "",
        "    /** The drawable layer. Valid only after init(). */",
        "    extern pixelroot32::graphics::TileMap4bpp terrain;",
        "",
        "    /**",
        "     * @brief Wires the descriptors above to the exported data.",
        "     *",
        "     * Idempotent, and cheap: it assigns pointers, it does not copy pixels.",
        "     * Call once before drawing.",
        "     */",
        "    void init();",
        "",
        f"}} // namespace {ns}",
        "} // namespace legend_of_clone",
        "",
        "#endif // PIXELROOT32_ENABLE_4BPP_SPRITES",
        "",
        f"#endif // {guard_h}",
        "",
    ]
    (OUT / f"{name}TileMap.h").write_text("\n".join(h), encoding="utf-8")

    # --- source ---
    c = [
        BANNER,
        f'#include "assets/{name}TileMap.h"',
        "",
        "#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES",
        "",
        f'#include "assets/{palette_header}"',
        '#include "platforms/PlatformMemory.h"',
        "",
        "namespace legend_of_clone {",
        f"namespace {ns} {{",
        "",
        "    // --- Tileset pixel data (4bpp) ---",
        "    // Two pixels per byte; the low nibble is the LEFT pixel of the pair.",
        f"    // {len(tiles)} tiles x {tile_bytes} bytes.",
        "    static const uint8_t PIXELROOT32_SCENE_FLASH_ATTR TILESET_DATA_POOL[] = {",
    ]
    for i, data in enumerate(packed):
        c.append(f"        // {tile_names[i]}")
        for r in range(0, len(data), art.ART_SIZE // 2):
            row = data[r:r + art.ART_SIZE // 2]
            c.append("        " + ", ".join(f"0x{b:02X}" for b in row) + ",")
    c += [
        "    };",
        "",
        "    static const pixelroot32::graphics::Sprite4bpp PIXELROOT32_SCENE_FLASH_ATTR TILESET_SPRITES[] = {",
    ]
    for i, tname in enumerate(tile_names):
        c.append(f"        {{ &TILESET_DATA_POOL[{i * tile_bytes}], {mapping_name}, "
                 f"TILE_SIZE, TILE_SIZE, 16 }}, // {tname}")
    c += [
        "    };",
        "",
        "    const bool TILE_SOLID[TILE_COUNT] = {",
    ]
    for tname, solid, _doc, _rows in tiles:
        c.append(f"        {'true ' if solid else 'false'}, // {tname}")
    c += [
        "    };",
        "",
        "    // --- Map indices ---",
    ]
    c.append("    static const uint8_t PIXELROOT32_SCENE_FLASH_ATTR TERRAIN_INDICES[] = {")
    for r, line in enumerate(rows):
        if len(line) != art.MAP_COLS:
            raise SystemExit(f"{name} map row {r} is {len(line)} chars, expected {art.MAP_COLS}")
        ids = []
        for ch in line:
            if ch not in legend:
                raise SystemExit(f"{name} map row {r} uses unmapped character {ch!r}")
            ids.append(tile_names.index(legend[ch]))
        c.append("        " + ", ".join(str(i) for i in ids) + f", // {r:2d} {line}")
    c += [
        "    };",
        "",
        "    pixelroot32::graphics::TileMap4bpp terrain;",
        "",
        "    void init() {",
        "        terrain.width      = MAP_WIDTH;",
        "        terrain.height     = MAP_HEIGHT;",
        "        terrain.tileWidth  = TILE_SIZE;",
        "        terrain.tileHeight = TILE_SIZE;",
        "        terrain.indices    = (uint8_t*)TERRAIN_INDICES;",
        "        terrain.tiles      = TILESET_SPRITES;",
        "        terrain.tileCount  = TILE_COUNT;",
        "    }",
        "",
        f"}} // namespace {ns}",
        "} // namespace legend_of_clone",
        "",
        "#endif // PIXELROOT32_ENABLE_4BPP_SPRITES",
        "",
    ]
    (OUT / f"{name}TileMap.cpp").write_text("\n".join(c), encoding="utf-8")


def emit_sprites(palette, mapping_name):
    guard = "CLONE_PLAYER_SPRITES_H"
    lines = [
        BANNER,
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "platforms/PlatformDefaults.h"',
        "",
        "#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES",
        "",
        '#include "graphics/Renderer.h"',
        '#include "assets/PlayerPalette.h"',
        "#include <stdint.h>",
        "",
        "/**",
        " * @file PlayerSprites.h",
        f" * @brief The hero: {len(art.PLAYER_SPRITES)} bitmaps covering four directions and a",
        " *        two-frame walk cycle.",
        " *",
        " * | Direction | Frame 0       | Frame 1                       |",
        " * |-----------|---------------|-------------------------------|",
        " * | South     | PLAYER_DOWN   | PLAYER_DOWN mirrored          |",
        " * | North     | PLAYER_UP     | PLAYER_UP mirrored            |",
        " * | East      | PLAYER_SIDE_A | PLAYER_SIDE_B - a real bitmap |",
        " * | West      | east, mirrored                                |",
        " *",
        " * Which frames are mirrors and which are not is MEASURED, not assumed - run",
        " * check_sprites.py. The two vertical directions mirror because the hero holds",
        " * nothing in either hand, so a flip has no held object to teleport across his",
        " * body; the side pair cannot, because mirroring a side-on pose turns him",
        " * around instead of animating him.",
        " *",
        " * There is no black in him. His outline, hair, boots and belt are one brown,",
        " * and with the tunic green and his skin that is three colors and a hole - one",
        " * NES sprite palette exactly, which is the entire budget a 1986 cartridge had",
        " * for a hero. Outlining a sprite in black is the fastest way to make it stop",
        " * reading as an 8-bit character.",
        " */",
        "",
        "namespace legend_of_clone {",
        "",
        f"    static const uint8_t PLAYER_WIDTH  = {art.ART_SIZE};",
        f"    static const uint8_t PLAYER_HEIGHT = {art.ART_SIZE};",
        "",
    ]

    for sname, sdoc, rows in art.PLAYER_SPRITES:
        words = to_words(pack(rows, palette))
        lines += doc_block(sdoc, "    ")
        lines.append(f"    static const uint16_t {sname}_4BPP[] = {{")
        per_row = art.ART_SIZE // 4
        for r in range(0, len(words), per_row):
            lines.append("        " + ", ".join(f"0x{w:04X}" for w in words[r:r + per_row]) + ",")
        lines.append("    };")
        lines.append("")

    lines += [
        "    /**",
        "     * @brief The five bitmaps as engine sprite descriptors.",
        "     *",
        "     * Index with PlayerFrame below rather than by number.",
        "     */",
        "    static const pixelroot32::graphics::Sprite4bpp PLAYER_FRAMES[] = {",
    ]
    for sname, _sdoc, _rows in art.PLAYER_SPRITES:
        lines.append(f"        {{ reinterpret_cast<const uint8_t*>({sname}_4BPP), "
                     f"{mapping_name}, PLAYER_WIDTH, PLAYER_HEIGHT, 16 }},")
    lines += [
        "    };",
        "",
        "    enum PlayerFrame : uint8_t {",
    ]
    for i, (sname, _sdoc, _rows) in enumerate(art.PLAYER_SPRITES):
        lines.append(f"        {sname} = {i},")
    lines += [
        "    };",
        "",
        "} // namespace legend_of_clone",
        "",
        "#endif // PIXELROOT32_ENABLE_4BPP_SPRITES",
        "",
        f"#endif // {guard}",
        "",
    ]
    (OUT / "PlayerSprites.h").write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------

tile_art = [t[3] for t in art.OVERWORLD_TILES] + [t[3] for t in art.DUNGEON_TILES]
palette = build_palette(tile_art)

sprite_palette = build_palette([s[2] for s in art.PLAYER_SPRITES])

emit_palette_header(
    OUT / "TilemapPalette.h", "CLONE_TILEMAP_PALETTE_H",
    "The 16 RGB565 colors both tilemaps render with.",
    "TILEMAP_PALETTE_DATA", "TILEMAP_PALETTE_MAPPING", palette,
    "Installed with setBackgroundCustomPalette(). The engine stores the pointer\n"
    "without copying, which is why this lives at namespace scope.\n"
    "\n"
    "Sampled to match the NES first-quest overworld: tan ground, the two greens\n"
    "of the bushes and forest, the navy drop shadow under every bush, and the two\n"
    "browns of the mountains.")

emit_palette_header(
    OUT / "PlayerPalette.h", "CLONE_PLAYER_PALETTE_H",
    "The RGB565 colors Link renders with.",
    "PLAYER_SPRITE_PALETTE_RGB565", "PLAYER_PALETTE_MAPPING", sprite_palette,
    "Installed with setSpriteCustomPalette(). Separate from the tilemap palette\n"
    "because dual palette mode gives sprites their own 16 slots - so the world\n"
    "and the hero are not competing for the same table.\n"
    "\n"
    "Three colors and a hole: exactly one NES sprite palette, which is the whole\n"
    "budget the 1986 cartridge had for its hero.")

emit_tilemap("Overworld", "overworld", art.OVERWORLD_TILES, art.OVERWORLD_MAP,
             art.OVERWORLD_MAP_LEGEND, "TilemapPalette.h", "TILEMAP_PALETTE_MAPPING",
             "Four adjacent overworld screens, 15x11 tiles each, laid out 2x2.")

emit_tilemap("Dungeon", "dungeon", art.DUNGEON_TILES, art.DUNGEON_MAP,
             art.DUNGEON_MAP_LEGEND, "TilemapPalette.h", "TILEMAP_PALETTE_MAPPING",
             "Four dungeon rooms on the same 2x2 grid the overworld uses.")

emit_sprites(sprite_palette, "PLAYER_PALETTE_MAPPING")

print(f"tilemap palette : {len(palette)} colors  {''.join(palette)}")
print(f"sprite palette  : {len(sprite_palette)} colors  {''.join(sprite_palette)}")
print(f"wrote 7 files to {OUT}")
