// Generated by tools/generate_pieces.py
// Engine: PixelRoot32
// Mode: 4bpp
// Source: ORIGINAL artwork for this demo (grids live in the generator).
//         Not derived from any third-party pack; free to redistribute.

#pragma once

#include <graphics/Color.h>

#include <cstdint>

namespace chessdemo {

using pixelroot32::graphics::Color;

/**
 * Colours every piece sprite resolves against, indexed by the nibble stored in
 * the sprite data. Index 0 is the transparent sentinel and is never drawn, so
 * its value only has to be *something*.
 *
 * These are checked against the board squares when they are generated: every
 * drawn colour has to stand at least a set distance from both kLightSquare and
 * kDarkSquare, and from the other colours in its own palette. Nothing in C++
 * notices a collision - the header compiles and the sprite draws, the outline
 * is just invisible on half the board - so the check lives in the generator and
 * fails the run instead. Change a colour there, not here.
 *
 * Two PR32 slots are deliberately avoided for piece pixels:
 *
 *   Color::Black resolves to RGB565 0x0000, and packRgb565ToTftSprite8(0x0000)
 *   is 0 - the value the 8bpp framebuffer treats as transparent. A black pixel
 *   therefore disappears on the ESP32 while still drawing on the SDL2 build.
 *   Color::Navy (#1B1F3B) is the darkest slot that survives the pack, so it
 *   plays the part of black here.
 *
 *   Color::Magenta is not magenta in this palette: it is #CECECE, a light grey,
 *   and it is the light board square. It was the rim on the dark pieces until
 *   that turned out to mean the rim and the square were the same colour.
 */
static constexpr uint8_t kPiecePaletteSize = 4;

static const Color kWhitePiecePalette[kPiecePaletteSize] = {
    Color::Black, // 0: transparent sentinel, never drawn
    Color::Navy,  // 1: outline - #1B1F3B
    Color::White, // 2: body - #FFFFFF
    Color::Gray   // 3: accent - #8D8D8D
};

static const Color kBlackPiecePalette[kPiecePaletteSize] = {
    Color::Black,  // 0: transparent sentinel, never drawn
    Color::Orange, // 1: outline - #FF9F1C
    Color::Navy,   // 2: body - #1B1F3B
    Color::Gray    // 3: accent - #8D8D8D
};

}  // namespace chessdemo
