// Generated by tools/generate_pieces.py
// Engine: PixelRoot32
// Source: the Wood entry in tools/generate_pieces.py PALETTES.

#pragma once

#include <cstdint>

namespace chessdemo {

/**
 * A full 16-slot RGB565 palette, in the layout the engine expects.
 *
 * This is PR32 with exactly two slots re-pointed - the two the board squares
 * use - which is the whole demonstration: a palette is a lookup table, so
 * changing two entries reskins the board without one line of drawing code
 * changing. The piece slots are untouched.
 *
 * It is generated rather than hand-written so check_contrast() can validate it
 * against the piece colours, exactly as it validates PR32. A hand-written table
 * here would be a palette nothing verifies.
 *
 * The engine stores the POINTER and never copies, so this must keep static
 * storage duration for as long as the palette is selected.
 */
static const uint16_t kChessCustomPalette[16] = {
    0x0000,  // 0  Black      #000000
    0xFFFF,  // 1  White      #FFFFFF
    0x1907,  // 2  Navy       #1B1F3B
    0x025F,  // 3  Blue       #0047FF
    0x061F,  // 4  Cyan       #00C2FF
    0x8AC5,  // 5  DarkGreen  #8B5A2B
    0x3648,  // 6  Green      #2ECC40
    0xA7F3,  // 7  LightGreen #A8FF9E
    0xFEA0,  // 8  Yellow     #FFD500
    0xFCE3,  // 9  Orange     #FF9F1C
    0xC3FF,  // 10 LightRed   #C77DFF
    0xB884,  // 11 Red        #C1121F
    0x6822,  // 12 DarkRed    #6A040F
    0x7977,  // 13 Purple     #7B2CBF
    0xD590,  // 14 Magenta    #D9B382
    0x8C71   // 15 Gray       #8D8D8D
};

}  // namespace chessdemo
