#ifndef ISOMETRIC_SCENE_MAIN_SCENE_H
#define ISOMETRIC_SCENE_MAIN_SCENE_H

#include <graphics/Renderer.h>
#include <physics/TileAttributes.h>
#include <math/Projection.h>
#include <stdint.h>
#include <string.h>

// PROGMEM compatibility macros are now provided by Renderer.h

/**
 * PixelRoot32 Exported Scene: New Scene - Main Scene
 * Generated by PixelRoot32 Tilemap Editor
 */

namespace isometric_scene::main_scene {

    using namespace pixelroot32::physics;

    // --- Tile Dimensions ---
    // TILE_WIDTH/TILE_HEIGHT are the CELL STRIDE, not the tileset's bitmap
    // extents. A tile may be -- and often is -- taller than its cell.
    inline constexpr uint8_t TILE_WIDTH  = 32;
    inline constexpr uint8_t TILE_HEIGHT = 16;
    inline constexpr uint8_t MAP_WIDTH   = 36;
    inline constexpr uint8_t MAP_HEIGHT  = 29;

    // --- Projection ---
    /// Where cell (0, 0)'s diamond CENTRE lands, and what one step along
    /// each cell axis does on screen: +1 cellX steps right and down,
    /// +1 cellY steps left and down.
    ///
    /// The origin is the diamond centre rather than a sprite corner because
    /// every anchor in TILESET_FOOT_Y is measured to that same point.
    inline constexpr pixelroot32::math::ProjectionSpec ISO_PROJECTION{
        464, 24,
         16,  8,
        -16,  8};

    static_assert(pixelroot32::math::projectionSpecIsValid(ISO_PROJECTION, MAP_WIDTH, MAP_HEIGHT),
                  "ISO_PROJECTION exceeds Scalar's fixed-point range for this map size.");
    static_assert(pixelroot32::math::projectionDet(ISO_PROJECTION) == 256,
                  "ISO_PROJECTION's determinant is no longer a power of two; "
                  "screenToCell would stop strength-reducing to a shift.");
    static_assert(pixelroot32::math::rowMajorIsPainterOrder(ISO_PROJECTION),
                  "ISO_PROJECTION no longer makes row-major iteration a back-to-front "
                  "paint order. The projected drawTileMap path has no depth sort and "
                  "relies on it.");

    // --- Tileset ---
    inline constexpr uint16_t TILESET_TILE_COUNT = 2;

    /// RGB565 palette the map's 4bpp tiles and sprites resolve against.
    /// Defined in the .cpp; index 0 is the transparent slot.
    extern const uint16_t CUSTOM_PALETTE_DATA[16];

    /// Bitmap row of each tile that lands on its cell's diamond centre.
    /// Parallel to TILESET_SPRITES. The orthogonal export has no analogue:
    /// its art fills its cell, so there is no anchor to record.
    extern const uint8_t TILESET_FOOT_Y[TILESET_TILE_COUNT];

    // --- Layer Definitions ---
    extern pixelroot32::graphics::TileMap4bpp ground;

    /**
     * Initializes the scene components.
     * Call this once before drawing in the render loop.
     */
    void init();

    // ============================================================================
    // PixelRoot32 Tile Behavior Layer (ESP32 Optimization)
    // Generated by PixelRoot32 Tilemap Editor
    // ============================================================================

    // --- Behavior Layer: Ground (36x29) ---

    /**
     * Dense behavior data array for layer "Ground".
     * Each byte contains TileFlags combination for the corresponding tile.
     * 0 = TILE_NONE (no behavior)
     */
    static const uint8_t TILE_BEHAVIOR_LAYER_GROUND[] PIXELROOT32_SCENE_FLASH_ATTR = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 0
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 1
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 2
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 3
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 4
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 5
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 6
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 7
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 8
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 9
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 10
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 11
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 12
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 13
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 14
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 15
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 16
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 17
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 18
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 19
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 20
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 21
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 22
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 23
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 24
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 25
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 26
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 27
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  // Row 28
    };

    // All behavior layers
    static const TileBehaviorLayer behavior_layers[] = {
        { TILE_BEHAVIOR_LAYER_GROUND, 36, 29 }    };

    static const uint8_t NUM_BEHAVIOR_LAYERS = 1;

    /**
     * Get TileFlags for a specific tile position in a behavior layer.
     * 
     * Args:
     *   layer_idx: Behavior layer index (0-based)
     *   x: X coordinate in tiles
     *   y: Y coordinate in tiles
     * 
     * Returns:
     *   TileFlags combination (0 = TILE_NONE if out of bounds)
     */
    inline uint8_t getTileFlags(uint8_t layer_idx, int x, int y) {
        if (layer_idx >= NUM_BEHAVIOR_LAYERS) {
            return 0; // TILE_NONE
        }
        
        const TileBehaviorLayer& layer = behavior_layers[layer_idx];
        if (x < 0 || x >= (int)layer.width || y < 0 || y >= (int)layer.height) {
            return 0; // TILE_NONE
        }
        
        return layer.data[y * layer.width + x];
    }

} // namespace isometric_scene::main_scene

#endif // ISOMETRIC_SCENE_MAIN_SCENE_H
