#!/usr/bin/env python3
"""Pack the ASCII art in art_source.py into the 4bpp headers the engine draws.

    python generate_assets.py [path/to/midway_clone]
    python generate_assets.py --check     # verify only, write nothing
    python generate_assets.py --preview   # print the art back as ASCII

Nothing here is compiled or shipped, and nothing here is versioned -
docs/audits/ is gitignored. This stands in for the PixelRoot32 Tilemap Editor
and Sprite Compiler: it takes an authoring format a human can edit and emits
the same C++ those tools emit, into the demo's src/assets/. That is
the same split legend_of_clone and metroidvania have; the output is what the
repository carries and what reviewers read.

Why a tool rather than hand-written headers:

The engine's 4bpp format packs two pixels per byte with the LOW nibble holding
the LEFT pixel (Renderer.cpp:605-606), and sprite rows are declared as
uint16_t. On a little-endian target that means the hex digits of a literal run
in the opposite order to the pixels they draw: 0x2220 is the pixel run 0,2,2,2.
Hand-authoring that is not difficult, it is merely impossible to do reliably -
every mirrored sprite is one transposed nibble away from a bug that looks like
an art mistake.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import art_source as art  # noqa: E402

# --------------------------------------------------------------------------
# Engine constants mirrored from the headers this output must satisfy
# --------------------------------------------------------------------------

# graphics/Color.h:58-75 - the blitter resolves sprite.palette[value] as one of
# these, then indexes the RGB565 table by the slot's numeric value.
COLOR_SLOTS = [
    "Black", "White", "Navy", "Blue",
    "Cyan", "DarkGreen", "Green", "LightGreen",
    "Yellow", "Orange", "LightRed", "Red",
    "DarkRed", "Purple", "Magenta", "Gray",
]

# Conventional value for every slot, applied before the art palette overrides
# it. Slots the art never touches keep these, so Color::Red still renders red
# for the debug overlay and for error text.
DEFAULT_SLOT_HEX = {
    "Black": "#000000", "White": "#FCFCFC", "Navy": "#0000A8", "Blue": "#0058F8",
    "Cyan": "#3CBCFC", "DarkGreen": "#007800", "Green": "#00A800", "LightGreen": "#B8F818",
    "Yellow": "#F8D878", "Orange": "#E45C10", "LightRed": "#F87858", "Red": "#F80000",
    "DarkRed": "#A81000", "Purple": "#6844FC", "Magenta": "#F878F8", "Gray": "#BCBCBC",
}

NAMESPACE = "midway_clone"
GUARD_PREFIX = "MIDWAY"

BANNER = """// Generated by the midway_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its ASCII art source are not versioned; see this example's
// README for what they are and where they live. Edit the art there and
// re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp
"""


# --------------------------------------------------------------------------
# Color
# --------------------------------------------------------------------------

def hex_to_rgb565(hex_str):
    """#RRGGBB -> RGB565, the layout the driver's palette LUT expects."""
    value = hex_str.lstrip("#")
    r, g, b = int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


class Palette:
    """One 16-slot palette plus the symbol -> 4bpp pixel value assignment.

    Pixel value 0 is the transparent hole and is never looked up, which is why
    the first art symbol lands at value 1 and not at 0.
    """

    def __init__(self, name, spec):
        self.name = name
        self.symbols = {".": 0}
        self.slot_of_value = {}
        self.notes = {}

        for index, (symbol, (slot, hex_str, description)) in enumerate(spec.items(), start=1):
            if symbol == ".":
                raise ValueError("'.' is reserved for the transparent hole")
            if slot not in COLOR_SLOTS:
                raise ValueError(f"{name}: '{symbol}' names unknown Color slot {slot!r}")
            self.symbols[symbol] = index
            self.slot_of_value[index] = slot
            self.notes[index] = (symbol, hex_str, description)

        if len(self.symbols) > 16:
            raise ValueError(f"{name}: {len(self.symbols)} symbols, 4bpp holds 16")

        self.slot_hex = dict(DEFAULT_SLOT_HEX)
        for _, (slot, hex_str, _desc) in spec.items():
            self.slot_hex[slot] = hex_str

    def value(self, symbol):
        if symbol not in self.symbols:
            raise ValueError(f"{self.name}: art uses undeclared symbol {symbol!r}")
        return self.symbols[symbol]

    def symbol_of_value(self, value):
        for symbol, packed in self.symbols.items():
            if packed == value:
                return symbol
        raise ValueError(f"{self.name}: no symbol for pixel value {value}")


# --------------------------------------------------------------------------
# 4bpp packing
# --------------------------------------------------------------------------

def pack_rows(rows, palette, expect_w, expect_h, label):
    """ASCII grid -> packed 4bpp bytes, low nibble first.

    Validates shape before packing. A grid that is one character short would
    otherwise pack into a sprite that renders with a diagonal shear, which is
    a confusing thing to debug from a screenshot.
    """
    if len(rows) != expect_h:
        raise ValueError(f"{label}: {len(rows)} rows, expected {expect_h}")
    if expect_w % 2 != 0:
        raise ValueError(f"{label}: width {expect_w} is odd; 4bpp packs pixel pairs")

    packed = bytearray()
    for y, row in enumerate(rows):
        if len(row) != expect_w:
            raise ValueError(f"{label}: row {y} is {len(row)} chars, expected {expect_w}")
        for x in range(0, expect_w, 2):
            left = palette.value(row[x])
            right = palette.value(row[x + 1])
            packed.append((left & 0x0F) | ((right & 0x0F) << 4))
    return bytes(packed)


def unpack_rows(packed, palette, width, height):
    """Inverse of pack_rows, used to prove the round trip."""
    rows = []
    stride = width // 2
    for y in range(height):
        row = []
        for x in range(stride):
            byte = packed[y * stride + x]
            row.append(palette.symbol_of_value(byte & 0x0F))
            row.append(palette.symbol_of_value((byte >> 4) & 0x0F))
        rows.append("".join(row))
    return rows


def verify(rows, packed, palette, width, height, label):
    restored = unpack_rows(packed, palette, width, height)
    if restored != list(rows):
        for y, (want, got) in enumerate(zip(rows, restored)):
            if want != got:
                raise AssertionError(
                    f"{label}: round trip differs at row {y}\n"
                    f"  source: {want}\n"
                    f"  packed: {got}"
                )
        raise AssertionError(f"{label}: round trip differs in row count")


# --------------------------------------------------------------------------
# C++ emission
# --------------------------------------------------------------------------

def emit_byte_pool(packed, per_row, indent="        "):
    lines = []
    for offset in range(0, len(packed), per_row):
        chunk = packed[offset:offset + per_row]
        lines.append(indent + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return lines


def emit_u16_rows(packed, width, height, indent="        "):
    """Sprite rows as uint16_t, which is how the existing examples declare them.

    Two packed bytes per uint16_t, low byte first: the array is reinterpret_cast
    to const uint8_t* at the point of use, so the literal has to match what a
    little-endian target reads back.
    """
    lines = []
    stride = width // 2
    for y in range(height):
        row = packed[y * stride:(y + 1) * stride]
        words = []
        for x in range(0, stride, 2):
            lo, hi = row[x], row[x + 1]
            words.append(f"0x{(lo | (hi << 8)):04X}")
        lines.append(indent + ", ".join(words) + ",")
    return lines


def emit_palette_header(palette, filename, struct_name, mapping_name, doc):
    guard = f"{GUARD_PREFIX}_{filename.upper().replace('.', '_')}"
    out = [BANNER, f"#ifndef {guard}", f"#define {guard}", "",
           '#include "graphics/Renderer.h"', "#include <stdint.h>", "",
           doc, "", f"namespace {NAMESPACE} {{", ""]

    out.append("    // --- RGB565 by engine Color slot ---")
    out.append("    // Indexed by Color, NOT by 4bpp pixel value. Slots the art never uses keep")
    out.append("    // their conventional color so Color::Red still renders red for text.")
    out.append(f"    static const uint16_t {struct_name}[16] = {{")
    used_slots = {slot for slot in palette.slot_of_value.values()}
    for index, slot in enumerate(COLOR_SLOTS):
        hex_str = palette.slot_hex[slot]
        rgb = hex_to_rgb565(hex_str)
        if slot in used_slots:
            symbol = next(s for v, s in
                          ((v, n[0]) for v, n in palette.notes.items())
                          if palette.slot_of_value[v] == slot)
            desc = next(n[2] for v, n in palette.notes.items()
                        if palette.slot_of_value[v] == slot)
            note = f"{slot}  '{symbol}'  {hex_str}  {desc}"
        else:
            note = f"{slot} - unused by art, conventional value kept"
        out.append(f"        0x{rgb:04X}, // {index:2d} {note}")
    out.append("    };")
    out.append("")

    out.append("    // --- 4bpp pixel value to engine Color slot ---")
    out.append("    // The blitter reads sprite.palette[pixelValue] as a Color and resolves that")
    out.append("    // slot against the table above. Entry 0 is never read: pixel value 0 is a")
    out.append("    // hole, so the first real color has to live at value 1.")
    out.append(f"    static const pixelroot32::graphics::Color {mapping_name}[16] = {{")
    for value in range(16):
        if value == 0:
            out.append("        pixelroot32::graphics::Color::Black, //  0 transparent - never read")
        elif value in palette.slot_of_value:
            slot = palette.slot_of_value[value]
            symbol = palette.notes[value][0]
            out.append(f"        pixelroot32::graphics::Color::{slot}, // {value:2d} '{symbol}' -> {slot}")
        else:
            out.append(f"        pixelroot32::graphics::Color::Black, // {value:2d} unused")
    out.append("    };")
    out.append("")
    out.append(f"}} // namespace {NAMESPACE}")
    out.append("")
    out.append(f"#endif // {guard}")
    out.append("")
    return "\n".join(out)


def wrap_doc(text, indent="     * "):
    return "\n".join(indent + line if line else indent.rstrip() for line in text.split("\n"))


# --------------------------------------------------------------------------
# Level
# --------------------------------------------------------------------------

class Lcg:
    """Deterministic 32-bit LCG (Numerical Recipes constants).

    A seeded generator rather than a hand-drawn map: the sea is 200 rows of
    mostly-identical water, and hand-placing six thousand tiles to get a
    scattering of whitecaps is data entry, not level design. The islands and
    the carrier ARE hand-placed, below - those are the parts a player reads.
    """

    def __init__(self, seed):
        self.state = seed & 0xFFFFFFFF

    def next(self):
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state

    def chance(self, one_in):
        return (self.next() >> 16) % one_in == 0


# 15x100 tiles at 16 px is 240x1600 px - the SAME world the 30x200 8px map
# described. That is deliberate: kCameraStartY, the stage length and every
# trigger in the wave table are in world pixels, so halving the grid while
# doubling the tile leaves all of them untouched.
LEVEL_WIDTH = 15
LEVEL_HEIGHT = 100

# (center row, center col, half-width, half-height, has_rock_core)
# Row 0 is the NORTH end of the stage. The camera starts at the bottom and
# climbs, so these are listed in the order the player meets them: last first.
#
# Halved from the 8px grid, radii included, so every island covers the same
# pixels it did before. Radii are small integers now, which costs some
# roundness - an island is a 5-tile blob rather than a 10-tile ellipse. That
# coarseness is the price of the tile size, and it shows up here rather than in
# the art.
ISLANDS = [
    (88, 3, 2, 2, False),
    (76, 11, 3, 2, True),
    (64, 6, 2, 2, False),
    (52, 12, 2, 3, True),
    (40, 3, 3, 2, True),
    (28, 8, 3, 2, True),
    (16, 4, 2, 2, False),
]

# The carrier that closes the stage: a deck plate the player crosses head-on.
# Three tiles wide by eight tall is 48x128 px - long enough that the deck fills
# half the screen's height while the player is over it.
CARRIER = (5, 12, 6, 8)  # (row_start, row_end, col_start, col_end) inclusive


def build_level(tile_id):
    ocean = tile_id["OCEAN"]
    wave = tile_id["OCEAN_WAVE"]
    foam = tile_id["FOAM"]
    sand = tile_id["SAND"]
    grass = tile_id["GRASS"]
    rock = tile_id["ROCK"]
    deck = tile_id["DECK"]

    grid = [[ocean] * LEVEL_WIDTH for _ in range(LEVEL_HEIGHT)]

    rng = Lcg(0x31393433)  # "1943"
    for y in range(LEVEL_HEIGHT):
        for x in range(LEVEL_WIDTH):
            if rng.chance(7):
                grid[y][x] = wave

    def ellipse(cy, cx, rx, ry, limit):
        cells = []
        for y in range(max(0, cy - ry - 2), min(LEVEL_HEIGHT, cy + ry + 3)):
            for x in range(max(0, cx - rx - 2), min(LEVEL_WIDTH, cx + rx + 3)):
                dx = (x - cx) / float(rx)
                dy = (y - cy) / float(ry)
                if dx * dx + dy * dy <= limit:
                    cells.append((y, x))
        return cells

    for cy, cx, rx, ry, has_rock in ISLANDS:
        for y, x in ellipse(cy, cx, rx, ry, 1.9):
            grid[y][x] = foam
        for y, x in ellipse(cy, cx, rx, ry, 1.0):
            grid[y][x] = sand
        for y, x in ellipse(cy, cx, rx, ry, 0.55):
            grid[y][x] = grass
        if has_rock:
            for y, x in ellipse(cy, cx, rx, ry, 0.18):
                grid[y][x] = rock

    r0, r1, c0, c1 = CARRIER
    # An inverted rectangle makes both range() calls below empty, which places
    # no deck at all and reports success. Ask loudly instead.
    if r1 < r0 or c1 < c0:
        raise ValueError(f"CARRIER rectangle is inverted: rows {r0}..{r1}, cols {c0}..{c1}")
    for cy, cx, rx, ry, _has_rock in ISLANDS:
        if not (0 <= cy < LEVEL_HEIGHT and 0 <= cx < LEVEL_WIDTH):
            raise ValueError(f"island centred at ({cy}, {cx}) falls outside the map")

    for y in range(max(0, r0 - 1), min(LEVEL_HEIGHT, r1 + 2)):
        for x in range(max(0, c0 - 1), min(LEVEL_WIDTH, c1 + 2)):
            grid[y][x] = foam
    for y in range(r0, r1 + 1):
        for x in range(c0, c1 + 1):
            grid[y][x] = deck

    return grid


# --------------------------------------------------------------------------
# Headers
# --------------------------------------------------------------------------

def build_tileset(bg_palette):
    packed_tiles = []
    for name, is_land, doc, rows in art.TILES:
        packed = pack_rows(rows, bg_palette, art.TILE_SIZE, art.TILE_SIZE, name)
        verify(rows, packed, bg_palette, art.TILE_SIZE, art.TILE_SIZE, name)
        packed_tiles.append((name, is_land, doc, rows, packed))
    return packed_tiles


def emit_tilemap_header(packed_tiles):
    guard = f"{GUARD_PREFIX}_OCEAN_TILEMAP_H"
    bytes_per_tile = art.TILE_SIZE * art.TILE_SIZE // 2

    out = [BANNER, f"#ifndef {guard}", f"#define {guard}", "",
           '#include "platforms/PlatformDefaults.h"', "",
           "#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES", "",
           '#include "graphics/Renderer.h"', "#include <stdint.h>", "",
           "/**",
           " * @file OceanTileMap.h",
           f" * @brief The stage: {LEVEL_WIDTH}x{LEVEL_HEIGHT} tiles of ocean, islands and one carrier.",
           " *",
           f" * Tiles are {art.TILE_SIZE}x{art.TILE_SIZE}, the same size legend_of_clone and metroidvania use.",
           " * The NES original is an 8x8 machine and this map was 8x8 first, which drew a",
           " * better coastline; it was doubled for frame rate. The renderer pays a per-tile",
           " * cost that does not shrink with the tile, so a 240x240 screen costs 900 blits",
           " * at 8px and 225 at 16px for the identical 57,600 pixels.",
           " *",
           " * Row 0 is the NORTH end of the stage. The camera starts at the bottom and",
           " * climbs, so the player meets the highest row numbers first.",
           " */", "",
           f"namespace {NAMESPACE} {{", "namespace ocean {", "",
           "    // --- Dimensions ---",
           f"    static const uint8_t  TILE_SIZE  = {art.TILE_SIZE};",
           f"    static const uint8_t  MAP_WIDTH  = {LEVEL_WIDTH};",
           f"    static const uint8_t  MAP_HEIGHT = {LEVEL_HEIGHT};",
           f"    static const uint16_t TILE_COUNT = {len(packed_tiles)};",
           "",
           "    // --- Tile ids ---",
           "    // 1-based: drawTileMap skips index 0, so slot 0 is reserved and never drawn.",
           ""]

    for index, (name, _is_land, doc, _rows, _packed) in enumerate(packed_tiles):
        out.append("    /**")
        out.append(wrap_doc(doc))
        out.append("     */")
        out.append(f"    static const uint8_t TILE_{name} = {index};")
        out.append("")

    out += ["    /**",
            "     * @brief Whether a tile is land, indexed by tile id.",
            "     *",
            "     * Nothing in this game collides with terrain - an aircraft overflies the",
            "     * whole map, which is why there is no TILE_SOLID table here the way",
            "     * legend_of_clone has one. This marks where ground targets can stand.",
            "     */",
            f"    extern const bool TILE_IS_LAND[TILE_COUNT];",
            "",
            "    /** The drawable layer. Valid only after init(). */",
            "    extern pixelroot32::graphics::TileMap4bpp sea;",
            "",
            "    /**",
            "     * @brief Wires the descriptors above to the exported data.",
            "     *",
            "     * Idempotent, and cheap: it assigns pointers, it does not copy pixels.",
            "     * Call once before drawing.",
            "     */",
            "    void init();",
            "",
            "} // namespace ocean",
            f"}} // namespace {NAMESPACE}",
            "",
            "#endif // PIXELROOT32_ENABLE_4BPP_SPRITES",
            "",
            f"#endif // {guard}",
            ""]
    return "\n".join(out), bytes_per_tile


def emit_tilemap_source(packed_tiles, bytes_per_tile, grid):
    out = [BANNER,
           '#include "assets/OceanTileMap.h"', "",
           "#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES", "",
           '#include "assets/TilemapPalette.h"',
           '#include "platforms/PlatformMemory.h"', "",
           f"namespace {NAMESPACE} {{", "namespace ocean {", "",
           "    // --- Tileset pixel data (4bpp) ---",
           "    // Two pixels per byte; the low nibble is the LEFT pixel of the pair.",
           f"    // {len(packed_tiles)} tiles x {bytes_per_tile} bytes.",
           "    static const uint8_t PIXELROOT32_SCENE_FLASH_ATTR TILESET_DATA_POOL[] = {"]

    for name, _is_land, _doc, _rows, packed in packed_tiles:
        out.append(f"        // TILE_{name}")
        out += emit_byte_pool(packed, art.TILE_SIZE // 2)
    out.append("    };")
    out.append("")

    out.append("    static const pixelroot32::graphics::Sprite4bpp PIXELROOT32_SCENE_FLASH_ATTR TILESET_SPRITES[] = {")
    for index, (name, _is_land, _doc, _rows, _packed) in enumerate(packed_tiles):
        offset = index * bytes_per_tile
        out.append(f"        {{ &TILESET_DATA_POOL[{offset}], TILEMAP_PALETTE_MAPPING, "
                   f"TILE_SIZE, TILE_SIZE, 16 }}, // TILE_{name}")
    out.append("    };")
    out.append("")

    out.append("    const bool TILE_IS_LAND[TILE_COUNT] = {")
    for name, is_land, _doc, _rows, _packed in packed_tiles:
        out.append(f"        {'true ' if is_land else 'false'}, // TILE_{name}")
    out.append("    };")
    out.append("")

    glyph = {index: name[0] for index, (name, _a, _b, _c, _d) in enumerate(packed_tiles)}
    glyph[0] = " "
    out.append("    // --- Map indices ---")
    out.append("    // The trailing comment renders each row: O ocean, o whitecap, F foam,")
    out.append("    // S sand, G grass, R rock, D carrier deck.")
    out.append("    static const uint8_t PIXELROOT32_SCENE_FLASH_ATTR SEA_INDICES[] = {")
    letters = {}
    for index, (name, _a, _b, _c, _d) in enumerate(packed_tiles):
        letters[index] = {
            "EMPTY": " ", "OCEAN": "O", "OCEAN_WAVE": "o", "FOAM": "F",
            "SAND": "S", "GRASS": "G", "ROCK": "R", "DECK": "D",
        }.get(name, name[0])
    for y, row in enumerate(grid):
        cells = ", ".join(f"{v}" for v in row)
        picture = "".join(letters[v] for v in row)
        out.append(f"        {cells}, // {y:3d} {picture}")
    out.append("    };")
    out.append("")

    out += ["    pixelroot32::graphics::TileMap4bpp sea;",
            "",
            "    void init() {",
            "        sea.width      = MAP_WIDTH;",
            "        sea.height     = MAP_HEIGHT;",
            "        sea.tileWidth  = TILE_SIZE;",
            "        sea.tileHeight = TILE_SIZE;",
            "        sea.indices    = (uint8_t*)SEA_INDICES;",
            "        sea.tiles      = TILESET_SPRITES;",
            "        sea.tileCount  = TILE_COUNT;",
            "    }",
            "",
            "} // namespace ocean",
            f"}} // namespace {NAMESPACE}",
            "",
            "#endif // PIXELROOT32_ENABLE_4BPP_SPRITES",
            ""]
    return "\n".join(out)


def emit_sprite_header(filename, doc, groups, palette, mapping_include, mapping_name):
    guard = f"{GUARD_PREFIX}_{filename.upper().replace('.', '_')}"
    out = [BANNER, f"#ifndef {guard}", f"#define {guard}", "",
           '#include "platforms/PlatformDefaults.h"', "",
           "#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES", "",
           '#include "graphics/Renderer.h"',
           f'#include "assets/{mapping_include}"',
           "#include <stdint.h>", "",
           doc, "",
           f"namespace {NAMESPACE} {{", ""]

    for group in groups:
        size = group["size"]
        out.append(f"    static const uint8_t {group['prefix']}_WIDTH  = {size};")
        out.append(f"    static const uint8_t {group['prefix']}_HEIGHT = {size};")
        out.append("")

        for name, frame_doc, rows in group["frames"]:
            packed = pack_rows(rows, palette, size, size, name)
            verify(rows, packed, palette, size, size, name)
            out.append("    /**")
            out.append(wrap_doc(frame_doc))
            out.append("     */")
            out.append(f"    static const uint16_t {name}_4BPP[] = {{")
            out += emit_u16_rows(packed, size, size)
            out.append("    };")
            out.append("")

        out.append("    /**")
        out.append(f"     * @brief {group['prefix']} frames as engine sprite descriptors.")
        out.append("     *")
        out.append(f"     * Index with {group['prefix']}Frame below rather than by number.")
        out.append("     */")
        out.append(f"    static const pixelroot32::graphics::Sprite4bpp {group['prefix']}_FRAMES[] = {{")
        for name, _doc, _rows in group["frames"]:
            out.append(f"        {{ reinterpret_cast<const uint8_t*>({name}_4BPP), {mapping_name}, "
                       f"{group['prefix']}_WIDTH, {group['prefix']}_HEIGHT, 16 }},")
        out.append("    };")
        out.append("")
        out.append(f"    enum {group['prefix']}Frame : uint8_t {{")
        for index, (name, _doc, _rows) in enumerate(group["frames"]):
            out.append(f"        {name} = {index},")
        out.append("    };")
        out.append("")
        out.append("    /**")
        out.append(f"     * @brief Frames in {group['prefix']}_FRAMES.")
        out.append("     *")
        out.append("     * Exported rather than left for callers to count, because the callers that")
        out.append("     * need it are animation loops deciding when a sequence has ended - and a")
        out.append("     * hand-written count is the kind that survives one frame being added.")
        out.append("     */")
        out.append(f"    static const uint8_t {group['prefix']}_FRAME_COUNT = {len(group['frames'])};")
        out.append("")

    out.append(f"}} // namespace {NAMESPACE}")
    out.append("")
    out.append("#endif // PIXELROOT32_ENABLE_4BPP_SPRITES")
    out.append("")
    out.append(f"#endif // {guard}")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# Preview
# --------------------------------------------------------------------------

# Two ASCII cells per pixel, so a 16px sprite prints at roughly its real aspect
# ratio in a terminal. ASCII rather than block-drawing characters because the
# Windows console this is most often run on encodes cp1252 and would raise on
# anything outside it - a preview that crashes is worse than a coarse one.
PREVIEW_INK = {
    ".": "  ", "k": "##", "n": "::", "b": "..", "c": "~~", "d": "vv",
    "g": "VV", "a": "--", "o": "oo", "r": "rr", "y": "==", "w": "@@",
    "s": "++", "h": "**", "f": "ff", "e": ",,",
}


def preview(rows, title):
    print(f"\n  {title}")
    for row in rows:
        print("    " + "".join(PREVIEW_INK.get(ch, "??") for ch in row))


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def locate_example():
    """Return the demo root - the directory holding src/.

    This script used to live under the engine's gitignored
    docs/audits/_dev_tools/, outside the tree it writes to, and walked up
    looking for examples/midway_clone. It now sits inside the demo itself, so
    the answer is the parent of this tools/ directory.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    candidate = os.path.dirname(here)
    if os.path.isdir(os.path.join(candidate, "src")):
        return candidate
    raise SystemExit(
        candidate + " does not look like the midway_clone demo (no src/ under "
        "it). This script expects to live in <demo>/tools/. Pass the demo path "
        "explicitly:\n    python generate_assets.py path/to/midway_clone")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("example", nargs="?", default=None,
                        help="path to the midway_clone demo; found automatically if omitted")
    parser.add_argument("--check", action="store_true", help="validate only, write nothing")
    parser.add_argument("--preview", action="store_true", help="print the art back as ASCII")
    args = parser.parse_args()

    example = args.example or locate_example()
    out_dir = os.path.join(example, "src", "assets")

    bg = Palette("TILEMAP_PALETTE", art.TILEMAP_PALETTE)
    sp = Palette("SPRITE_PALETTE", art.SPRITE_PALETTE)

    packed_tiles = build_tileset(bg)
    grid = build_level({name: index for index, (name, _a, _b, _c, _d) in enumerate(packed_tiles)})

    tilemap_h, bytes_per_tile = emit_tilemap_header(packed_tiles)
    tilemap_cpp = emit_tilemap_source(packed_tiles, bytes_per_tile, grid)

    tilemap_palette_h = emit_palette_header(
        bg, "TilemapPalette.h", "TILEMAP_PALETTE_DATA", "TILEMAP_PALETTE_MAPPING",
        "/**\n"
        " * @file TilemapPalette.h\n"
        " * @brief The 16 RGB565 colors the sea and the islands render with.\n"
        " *\n"
        " * Installed with setBackgroundCustomPalette(). The engine stores the pointer\n"
        " * without copying, which is why this lives at namespace scope.\n"
        " *\n"
        " * Sampled against the NES palette: three blues for water depth, one cyan for\n"
        " * foam, and the same sand and rock browns any 8-bit island is built from.\n"
        " */")

    sprite_palette_h = emit_palette_header(
        sp, "SpritePalette.h", "SPRITE_PALETTE_DATA", "SPRITE_PALETTE_MAPPING",
        "/**\n"
        " * @file SpritePalette.h\n"
        " * @brief The 16 RGB565 colors every aircraft, tracer and explosion draws with.\n"
        " *\n"
        " * Installed with setSpriteCustomPalette(). Separate from the tilemap palette\n"
        " * because dual palette mode gives sprites their own 16 slots - so the sea and\n"
        " * the aircraft are not competing for the same table.\n"
        " *\n"
        " * Player and enemy share no color except black. On a screen holding a dozen\n"
        " * aircraft that is what keeps the two apart at a glance.\n"
        " */")

    player_h = emit_sprite_header(
        "PlayerSprites.h",
        "/**\n"
        " * @file PlayerSprites.h\n"
        " * @brief The player's P-38: level flight with a two-frame propeller, plus a\n"
        " *        banked frame each way.\n"
        " *\n"
        " * The twin-boom silhouette was picked over a single-engine fighter because at\n"
        " * 16x16 an aircraft has about a 12x14 usable footprint, and a shape with two\n"
        " * hard vertical lines through it stays legible against a moving sea. A single\n"
        " * fuselage at this size is a blob.\n"
        " *\n"
        " * Only the propeller hub pixels differ between the two level frames. A\n"
        " * propeller does not need to be drawn, it needs to flicker.\n"
        " */",
        [{"prefix": "PLAYER", "size": art.PLAYER_SPRITE_SIZE, "frames": art.PLAYER_FRAMES}],
        sp, "SpritePalette.h", "SPRITE_PALETTE_MAPPING")

    enemy_h = emit_sprite_header(
        "EnemySprites.h",
        "/**\n"
        " * @file EnemySprites.h\n"
        " * @brief Enemy aircraft, drawn nose-south - flying at the player, which is the\n"
        " *        only direction they ever travel.\n"
        " */",
        [{"prefix": "ENEMY", "size": art.ENEMY_SPRITE_SIZE, "frames": art.ENEMY_FRAMES}],
        sp, "SpritePalette.h", "SPRITE_PALETTE_MAPPING")

    effects_h = emit_sprite_header(
        "EffectSprites.h",
        "/**\n"
        " * @file EffectSprites.h\n"
        " * @brief Tracers and explosions.\n"
        " *\n"
        " * Projectiles are 8x8: a bullet is read by its color and its motion, never by\n"
        " * its shape, so spending 16x16 on one would cost four times the blit for\n"
        " * nothing. Player fire is a yellow vertical stroke, enemy fire a red disc -\n"
        " * shape and color both differ, so the distinction survives for a colorblind\n"
        " * player.\n"
        " */",
        [{"prefix": "BULLET", "size": art.PROJECTILE_SIZE, "frames": art.PROJECTILES},
         {"prefix": "EXPLOSION", "size": art.EXPLOSION_SIZE, "frames": art.EXPLOSION_FRAMES}],
        sp, "SpritePalette.h", "SPRITE_PALETTE_MAPPING")

    if args.preview:
        for name, _is_land, _doc, rows, _packed in packed_tiles:
            if name != "EMPTY":
                preview(rows, f"TILE_{name}")
        for name, _doc, rows in art.PLAYER_FRAMES + art.ENEMY_FRAMES:
            preview(rows, name)
        for name, _doc, rows in art.PROJECTILES + art.EXPLOSION_FRAMES:
            preview(rows, name)

    files = {
        "TilemapPalette.h": tilemap_palette_h,
        "SpritePalette.h": sprite_palette_h,
        "OceanTileMap.h": tilemap_h,
        "OceanTileMap.cpp": tilemap_cpp,
        "PlayerSprites.h": player_h,
        "EnemySprites.h": enemy_h,
        "EffectSprites.h": effects_h,
    }

    if args.check:
        print("art validated; round trip clean; nothing written")
    else:
        os.makedirs(out_dir, exist_ok=True)
        for filename, content in files.items():
            with open(os.path.join(out_dir, filename), "w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
            print(f"wrote {os.path.join(out_dir, filename)}  ({len(content):,} bytes)")

    tileset_bytes = len(packed_tiles) * bytes_per_tile
    level_bytes = LEVEL_WIDTH * LEVEL_HEIGHT
    sprite_count = (len(art.PLAYER_FRAMES) + len(art.ENEMY_FRAMES) + len(art.EXPLOSION_FRAMES))
    sprite_bytes = sprite_count * (art.PLAYER_SPRITE_SIZE ** 2 // 2)
    sprite_bytes += len(art.PROJECTILES) * (art.PROJECTILE_SIZE ** 2 // 2)

    print("")
    print(f"  tileset   {len(packed_tiles):3d} tiles   {tileset_bytes:6,d} B flash")
    print(f"  level     {LEVEL_WIDTH}x{LEVEL_HEIGHT}       {level_bytes:6,d} B flash")
    print(f"  sprites   {sprite_count + len(art.PROJECTILES):3d} frames  {sprite_bytes:6,d} B flash")
    print(f"  total                  {tileset_bytes + level_bytes + sprite_bytes:6,d} B flash, 0 B SRAM")


if __name__ == "__main__":
    main()
