/*
 * Trig.cpp - see Trig.h.
 *
 * kSinQ14 is a generated golden: it is produced by tools/gen_sin_table.py
 * (Python standard library only) and committed here as a literal. The C++
 * build never invokes Python; regenerate and re-paste this array only if the
 * angle resolution or the Q14 scale changes (see the script's docstring).
 */
#include "pool/Trig.h"

namespace pool {

namespace {

// kSinQ14[i] = round(16384 * sin(i * 2*pi / 1024)) for i in 0..256: one
// quarter of a revolution (0..90 degrees), Q14 fixed point (16384 = 1.0).
// Generated by tools/gen_sin_table.py.
constexpr int16_t kSinQ14[257] = {
    0, 101, 201, 302, 402, 503, 603, 704,
    804, 904, 1005, 1105, 1205, 1306, 1406, 1506,
    1606, 1706, 1806, 1906, 2006, 2105, 2205, 2305,
    2404, 2503, 2603, 2702, 2801, 2900, 2999, 3098,
    3196, 3295, 3393, 3492, 3590, 3688, 3786, 3883,
    3981, 4078, 4176, 4273, 4370, 4467, 4563, 4660,
    4756, 4852, 4948, 5044, 5139, 5235, 5330, 5425,
    5520, 5614, 5708, 5803, 5897, 5990, 6084, 6177,
    6270, 6363, 6455, 6547, 6639, 6731, 6823, 6914,
    7005, 7096, 7186, 7276, 7366, 7456, 7545, 7635,
    7723, 7812, 7900, 7988, 8076, 8163, 8250, 8337,
    8423, 8509, 8595, 8680, 8765, 8850, 8935, 9019,
    9102, 9186, 9269, 9352, 9434, 9516, 9598, 9679,
    9760, 9841, 9921, 10001, 10080, 10159, 10238, 10316,
    10394, 10471, 10549, 10625, 10702, 10778, 10853, 10928,
    11003, 11077, 11151, 11224, 11297, 11370, 11442, 11514,
    11585, 11656, 11727, 11797, 11866, 11935, 12004, 12072,
    12140, 12207, 12274, 12340, 12406, 12472, 12537, 12601,
    12665, 12729, 12792, 12854, 12916, 12978, 13039, 13100,
    13160, 13219, 13279, 13337, 13395, 13453, 13510, 13567,
    13623, 13678, 13733, 13788, 13842, 13896, 13949, 14001,
    14053, 14104, 14155, 14206, 14256, 14305, 14354, 14402,
    14449, 14497, 14543, 14589, 14635, 14680, 14724, 14768,
    14811, 14854, 14896, 14937, 14978, 15019, 15059, 15098,
    15137, 15175, 15213, 15250, 15286, 15322, 15357, 15392,
    15426, 15460, 15493, 15525, 15557, 15588, 15619, 15649,
    15679, 15707, 15736, 15763, 15791, 15817, 15843, 15868,
    15893, 15917, 15941, 15964, 15986, 16008, 16029, 16049,
    16069, 16088, 16107, 16125, 16143, 16160, 16176, 16192,
    16207, 16221, 16235, 16248, 16261, 16273, 16284, 16295,
    16305, 16315, 16324, 16332, 16340, 16347, 16353, 16359,
    16364, 16369, 16373, 16376, 16379, 16381, 16383, 16384,
    16384,
};

}  // namespace

int32_t sinQ14(uint16_t angle) {
    const uint16_t wrapped = static_cast<uint16_t>(angle % kAngleSteps);
    const uint16_t quadrant = static_cast<uint16_t>(wrapped / 256u);
    const uint16_t offset = static_cast<uint16_t>(wrapped % 256u);

    switch (quadrant) {
        case 0: return kSinQ14[offset];
        case 1: return kSinQ14[256u - offset];
        case 2: return -kSinQ14[offset];
        default: return -kSinQ14[256u - offset];  // quadrant 3
    }
}

int32_t cosQ14(uint16_t angle) {
    return sinQ14(static_cast<uint16_t>((angle + 256u) % kAngleSteps));
}

}  // namespace pool
